<?php
/*
 var db =  {
 'id': '<?php echo $id ?>',
 'StaffID2': '<?php echo $StaffID2 ?>',
 StaffName: '<?php echo $StaffName ?>',
 StaffDept: '<?php echo $StaffDept ?>',
 WorkStt: '<?php echo $WorkStt ?>',
 JP: '<?php echo $JP ?>',
 StaffOffice: '<?php echo $StaffOffice ?>',
 staffBranch: '<?php echo $staffBranch ?>',
 LastName: '<?php echo $LastName ?>',
 MiddleName: '<?php echo $MiddleName ?>',
 FirstName: '<?php echo $FirstName ?>',
 DOB: '<?php echo $DOB ?>',
 JoinedDate: '<?php echo $JoinedDate ?>',
 ResignedDate: '<?php echo $ResignedDate ?>',
 Note: '<?php echo $Note ?>',
 Email: '<?php echo $Email ?>',
 EmailRQ: '<?php echo $EmailRQ ?>',
 EmailCreate: '<?php echo $EmailCreate ?>',
 EmailCLC: '<?php echo $EmailCLC ?>',
 Domain: '<?php echo $Domain ?>',
 Alias1: '<?php echo $Alias1 ?>',
 Alias2: '<?php echo $Alias2 ?>',
 EmailHistory: '<?php echo $EmailHistory ?>',
 AD: '<?php echo $AD ?>',
 ADCreate: '<?php echo $ADCreate ?>',
 ADCLC: '<?php echo $ADCLC ?>',
 Nippo: '<?php echo $Nippo ?>',
 NippoRQ: '<?php echo $NippoRQ ?>',
 NippoCreate: '<?php echo $NippoCreate ?>',
 NippoCLC: '<?php echo $NippoCLC ?>',
 Hisgo: '<?php echo $Hisgo ?>',
 HisgoRQ: '<?php echo $HisgoRQ ?>',
 HisgoCreate: '<?php echo $HisgoCreate ?>',
 HisgoCLC: '<?php echo $HisgoCLC ?>',
 Challenge: '<?php echo $ChallengeRQ ?>',
 ChallengeRQ: '<?php echo $ChallengeRQ ?>',
 ChallengeCreate: '<?php echo $ChallengeCreate ?>',
 ChallengeCLC: '<?php echo $ChallengeCLC ?>',
 Vacation: '<?php echo $Vacation ?>',
 VacationRQ: '<?php echo $VacationRQ ?>',
 VacationCreate: '<?php echo $VacationCreate ?>',
 VacationCLC: '<?php echo $VacationCLC ?>',
 Other: '<?php echo $Other ?>'
 };
 */